"""Add approval_token to User model

Revision ID: 21ef9d458665
Revises: a2736edb1f29
Create Date: 2025-04-29 22:50:15.756198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ef9d458665'
down_revision = 'a2736edb1f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['approval_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('approval_token')

    # ### end Alembic commands ###
