"""Add discount_percent to Product

Revision ID: 5fffc964187e
Revises: 21ef9d458665
Create Date: 2025-04-30 22:44:55.618603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fffc964187e'
down_revision = '21ef9d458665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percent', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('discount_percent')

    # ### end Alembic commands ###
