"""Add custom_order_id to orders

Revision ID: a2736edb1f29
Revises: 2b4dc721ffe8
Create Date: 2025-04-25 16:09:25.980695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2736edb1f29'
down_revision = '2b4dc721ffe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_order_id', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['custom_order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('custom_order_id')

    # ### end Alembic commands ###
