"""Add products and orders table

Revision ID: dfdcbeb454bc
Revises: 
Create Date: 2025-03-19 23:19:59.808076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfdcbeb454bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Pending'"))
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('order_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('orders_ibfk_1', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Pending'"))
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_name')
        batch_op.drop_column('customer_email')

    # ### end Alembic commands ###
