"""Remove discount_percent from Product

Revision ID: e4d2dc5bf6e9
Revises: 5fffc964187e
Create Date: 2025-04-30 23:02:51.867817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4d2dc5bf6e9'
down_revision = '5fffc964187e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('discount_percent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percent', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
